// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hadvummsmttmivuznbjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhZHZ1bW1zbXR0bWl2dXpuYmpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDc3ODksImV4cCI6MjA2ODY4Mzc4OX0.NCM3E_RCpDPwr9xyDsedRr03lQCDvj0A7do736K9qdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});